### ISSUE TITLE
Support Draft 2019-09

### ISSUE THREAD

**Issue by CarstenWickner** [victools/jsonschema-generator#14]
A new draft 8 (or now officially: "2019-09") has been published and there appear to be only two relevant changes for the schema generation before being able to claim compatibility:
- [x] new `$schema` value (`"https://json-schema.org/draft/2019-09/schema"`) #44
- [x] `definitions` is now `$defs` (`definitions` is still allowed for compatibility reasons, but deprecated) #44

One other interesting change is the following one, which would allow for less `allOf` wrappers being necessary but is only a nice-to-have (as it complicates the handling of these things):
- [x] `$ref` – Other keywords are now allowed alongside it #47

Everything else is either related to the schema validation, hyper schemas, or elements of the core schema that are currently not being used here.

Refer to https://json-schema.org/draft/2019-09/release-notes.html for details.

**Comment by CarstenWickner** [comment]
This has been released in [v4.6.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.6.0).
